import { createContext, useReducer } from "react";
import AppReducer from "./AppReducer";

const initialState = {
  users: [
    {
      hospitalName: "Crimson Hospital",
      id: 1,
      state: "ilorin",
      address: "Tanke",
      city: "ilorin",
      activity: "Loose and Floppy muscle tones",
      pulse: " less than 100 bpm",
      grimace: "Floppy or No reaction",
      appearance: "Blue Pale",
      respiration: "Absent",
      score: 1,
      comment: "Severely Depressed",
      motherID: "02",
      deliveryMode: "SVG",
      gestationPeriod: "10 weeks",
      birthWeight: "20kg",
      maternalHtpertension: "No",
      fetalPosition: "Normal",
      MSL: "Normal",
      activityScore: "0",
      pulseScore: 1,
      grimaceScore: "0",
      appearanceScore: "0",
      respirationScore: "0",
      notificationMessage: "An APGAR score of ID no 01 has been recorded",
      image: require("../images/Home/baby1.png"),
    },
    {
      hospitalName: "Crimson Hospital",
      id: 2,
      state: "ilorin",
      address: "Tanke",
      city: "ilorin",
      activity: "Active motion",
      pulse: "greater than 100 bpm",
      grimace: "Prompt response",
      appearance: "pink",
      respiration: "Vigorous Cry",
      score: 10,
      comment: "Severely Depressed",
      motherID: "02",
      deliveryMode: "SVG",
      gestationPeriod: "10 weeks",
      birthWeight: "20kg",
      maternalHtpertension: "No",
      fetalPosition: "Normal",
      MSL: "Normal",
      activityScore: 2,
      pulseScore: 2,
      grimaceScore: 2,
      appearanceScore: 2,
      respirationScore: 2,
      notificationMessage: "An APGAR score of ID no 02 has been recorded",
      image: require("../images/Home/baby2.png"),
    },
    {
      hospitalName: "Crimson Hospital",
      id: 3,
      state: "ilorin",
      address: "Tanke",
      city: "ilorin",
      activity: "Flexed arms and legs",
      pulse: " less than 100 bpm",
      grimace: "Minimal response",
      appearance: "Blue extremeties",
      respiration: "slow and irregular",
      score: 5,
      comment: "Severely Depressed",
      motherID: "02",
      deliveryMode: "SVG",
      gestationPeriod: "10 weeks",
      birthWeight: "20kg",
      maternalHtpertension: "No",
      fetalPosition: "Normal",
      MSL: "Normal",
      activityScore: 1,
      pulseScore: 1,
      grimaceScore: 1,
      appearanceScore: 1,
      respirationScore: 1,
      notificationMessage: "An APGAR score of ID no 03 has been recorded",
      image: require("../images/Home/baby3.png"),
    },
    {
      hospitalName: "Crimson Hospital",
      id: 4,
      state: "ilorin",
      address: "Tanke",
      city: "ilorin",
      activity: "Loose and Floppy muscle tones",
      pulse: " less than 100 bpm",
      grimace: "Floppy or No reaction",
      appearance: "Blue Pale",
      respiration: "Absent",
      score: 1,
      comment: "Severely Depressed",
      motherID: "02",
      deliveryMode: "SVG",
      gestationPeriod: "10 weeks",
      birthWeight: "20kg",
      maternalHtpertension: "No",
      fetalPosition: "Normal",
      MSL: "Normal",
      activityScore: 0,
      pulseScore: 1,
      grimaceScore: 0,
      appearanceScore: 0,
      respirationScore: 0,
      notificationMessage: "An APGAR score of ID no 04 has been recorded",
      image: require("../images/Home/baby4.png"),
    },
    {
      hospitalName: "Crimson Hospital",
      id: 5,
      state: "ilorin",
      address: "Tanke",
      city: "ilorin",
      activity: "Loose and Floppy muscle tones",
      pulse: "less 100 bpm",
      grimace: "Floppy or No reaction",
      appearance: "Blue Pale",
      respiration: "Absent",
      score: 1,
      motherID: "02",
      comment: "Severely Depressed",
      deliveryMode: "SVG",
      gestationPeriod: "10 weeks",
      birthWeight: "20kg",
      maternalHtpertension: "No",
      fetalPosition: "Normal",
      MSL: "Normal",
      activityScore: 0,
      pulseScore: 1,
      grimaceScore: 0,
      appearanceScore: 0,
      respirationScore: 0,
      notificationMessage: "An APGAR score of ID no 05 has been recorded",
      image: require("../images/Home/baby3.png"),
    },
    {
      hospitalName: "Crimson Hospital",
      id: 6,
      state: "ilorin",
      address: "Tanke",
      city: "ilorin",
      activity: "Loose and Floppy muscle tones",
      pulse: "less than 100 bpm",
      grimace: "Floppy or No reaction",
      appearance: "Blue Pale",
      respiration: "Absent",
      score: 1,
      comment: "Severely Depressed",
      motherID: "02",
      deliveryMode: "SVG",
      gestationPeriod: "10 weeks",
      birthWeight: "20kg",
      maternalHtpertension: "No",
      fetalPosition: "Normal",
      MSL: "Normal",
      activityScore: 0,
      pulseScore: 1,
      grimaceScore: 0,
      appearanceScore: 0,
      respirationScore: 0,
      notificationMessage: "An APGAR score of ID no 06 has been recorded",
      image: require("../images/Home/baby2.png"),
    },
    {
      hospitalName: "Crimson Hospital",
      id: 7,
      state: "ilorin",
      address: "Tanke",
      city: "ilorin",
      activity: "Loose and Floppy muscle tones",
      pulse: "less than 100 bpm",
      grimace: "Floppy or No reaction",
      appearance: "Blue Pale",
      respiration: "Absent",
      score: 1,
      comment: "Severely Depressed",
      motherID: "02",
      deliveryMode: "SVG",
      gestationPeriod: "10 weeks",
      birthWeight: "20kg",
      maternalHtpertension: "No",
      fetalPosition: "Normal",
      MSL: "Normal",
      activityScore: 0,
      pulseScore: 1,
      grimaceScore: 0,
      appearanceScore: 0,
      respirationScore: 0,
      notificationMessage: "An APGAR score of ID no 07 has been recorded",
      image: require("../images/Home/baby1.png"),
    },
  ],
};
export const GlobalContext = createContext(initialState);

export const GlobalProvider = ({ children }) => {
  const [state, dispatch] = useReducer(AppReducer, initialState);

  // action

  const deleteTodo = (id) => {
    dispatch({
      type: "DELETE_TODO",
      payload: id,
    });
  };

  const addUser = (user) => {
    dispatch({
      type: "ADD_USER",
      payload: user,
    });
  };

  return (
    <GlobalContext.Provider
      value={{
        users: state.users,
        deleteTodo,
        addUser,
      }}
    >
      {children}
    </GlobalContext.Provider>
  );
};
